/*
 * (C) Copyright 2017 Arsi (http://www.arsi.sk/).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.netbeans.modules.editor.completion;

import javax.swing.JLabel;

/**
 *
 * @author arsi
 */
public class RankView extends javax.swing.JPanel {

    /**
     * Creates new form RankView
     */
    public RankView() {
        initComponents();
    }

    public void setRank(int rank) {
        switch (rank) {
            case 0:
                setLabelRank(rank1, false);
                setLabelRank(rank2, false);
                setLabelRank(rank3, false);
                setLabelRank(rank4, false);
                setLabelRank(rank5, false);
                break;
            case 1:
                setLabelRank(rank1, true);
                setLabelRank(rank2, false);
                setLabelRank(rank3, false);
                setLabelRank(rank4, false);
                setLabelRank(rank5, false);
                break;
            case 2:
                setLabelRank(rank1, true);
                setLabelRank(rank2, true);
                setLabelRank(rank3, false);
                setLabelRank(rank4, false);
                setLabelRank(rank5, false);
                break;
            case 3:
                setLabelRank(rank1, true);
                setLabelRank(rank2, true);
                setLabelRank(rank3, true);
                setLabelRank(rank4, false);
                setLabelRank(rank5, false);
                break;
            case 4:
                setLabelRank(rank1, true);
                setLabelRank(rank2, true);
                setLabelRank(rank3, true);
                setLabelRank(rank4, true);
                setLabelRank(rank5, false);
                break;
            case 5:
                setLabelRank(rank1, true);
                setLabelRank(rank2, true);
                setLabelRank(rank3, true);
                setLabelRank(rank4, true);
                setLabelRank(rank5, true);
                break;
        }
    }

    private void setLabelRank(JLabel label, boolean on) {
        if (on) {
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N
        } else {
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank_off.png"))); // NOI18N

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rank1 = new javax.swing.JLabel();
        rank2 = new javax.swing.JLabel();
        rank3 = new javax.swing.JLabel();
        rank4 = new javax.swing.JLabel();
        rank5 = new javax.swing.JLabel();

        rank1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N

        rank2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N

        rank3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N

        rank4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N

        rank5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/editor/completion/resources/rank.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rank1)
                .addGap(0, 0, 0)
                .addComponent(rank2)
                .addGap(0, 0, 0)
                .addComponent(rank3)
                .addGap(0, 0, 0)
                .addComponent(rank4)
                .addGap(0, 0, 0)
                .addComponent(rank5)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rank1)
                    .addComponent(rank2)
                    .addComponent(rank3)
                    .addComponent(rank4)
                    .addComponent(rank5))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rank1;
    private javax.swing.JLabel rank2;
    private javax.swing.JLabel rank3;
    private javax.swing.JLabel rank4;
    private javax.swing.JLabel rank5;
    // End of variables declaration//GEN-END:variables
}
