/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.arsi.nb.help.module.actions;

import javax.swing.ImageIcon;
import org.openide.util.NbPreferences;

/**
 *
 * @author arsi
 */
public class SearchSelector extends javax.swing.JPanel {

    public static final String FULLTEXT = "FULLTEXT";
    private final String prefix;
    private final ImageIcon kOn = new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_k.png"));
    private final ImageIcon kOff = new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_k_off.png"));
    private final ImageIcon fOn = new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_F.png"));
    private final ImageIcon fOff = new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_F_off.png"));

    public final boolean isFullText() {
        return NbPreferences.forModule(SearchSelector.class).getBoolean(FULLTEXT + prefix, NbPreferences.forModule(ServerSelector.class).getBoolean(FULLTEXT, false));
    }

    /**
     * Creates new form SearchSelector
     */
    public SearchSelector() {
        this("");
    }

    public SearchSelector(String prefix) {
        initComponents();
        this.prefix = prefix;
        if (isFullText()) {
            buttonF.setIcon(fOn);
            buttonK.setIcon(kOff);
        } else {
            buttonF.setIcon(fOff);
            buttonK.setIcon(kOn);
        }
        buttonF.setContentAreaFilled(false);
        buttonK.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonK = new javax.swing.JButton();
        buttonF = new javax.swing.JButton();

        buttonK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_k.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(buttonK, org.openide.util.NbBundle.getMessage(SearchSelector.class, "SearchSelector.buttonK.text")); // NOI18N
        buttonK.setToolTipText(org.openide.util.NbBundle.getMessage(SearchSelector.class, "SearchSelector.buttonK.toolTipText")); // NOI18N
        buttonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKActionPerformed(evt);
            }
        });

        buttonF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/arsi/nb/help/module/letter_F_off.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(buttonF, org.openide.util.NbBundle.getMessage(SearchSelector.class, "SearchSelector.buttonF.text")); // NOI18N
        buttonF.setToolTipText(org.openide.util.NbBundle.getMessage(SearchSelector.class, "SearchSelector.buttonF.toolTipText")); // NOI18N
        buttonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonK, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonK, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFActionPerformed
        // TODO add your handling code here:
        NbPreferences.forModule(SearchSelector.class).putBoolean(FULLTEXT, true);
        NbPreferences.forModule(SearchSelector.class).putBoolean(FULLTEXT + prefix, true);
        buttonF.setIcon(fOn);
        buttonK.setIcon(kOff);
    }//GEN-LAST:event_buttonFActionPerformed

    private void buttonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKActionPerformed
        // TODO add your handling code here:
        NbPreferences.forModule(SearchSelector.class).putBoolean(FULLTEXT, false);
        NbPreferences.forModule(SearchSelector.class).putBoolean(FULLTEXT + prefix, false);
        buttonF.setIcon(fOff);
        buttonK.setIcon(kOn);
    }//GEN-LAST:event_buttonKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonK;
    // End of variables declaration//GEN-END:variables
}
